version: '3.4'

services:
  ClashRoyaleApi:
    image: ${DOCKER_REGISTRY-}clashroyaleapi
    environment:
      - TZ=Europe/Amsterdam
      - TimeStamp=16:00
    ports: 
        - 5050:80
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '1.5g'
        reservations:
          cpus: '1'
          memory: '500M' 
    build:
      context: .
      dockerfile: /ClashRoyaleApi/ClashRoyaleApi/Dockerfile
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    container_name: backend-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1g'
        reservations:
          cpus: '0.5'
          memory: '500M' 
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '250M'
        reservations:
          cpus: '0.25'
          memory: '100M' 
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data: